from odoo import _, fields, models, api


class AdditionalDataSegment(models.Model):
    _name = "additional.data.segment"
    _description = 'Additional Data Segment'

    name = fields.Char(
        string="Name",
        required=True,
        compute='_compute_name'
    )

    color = fields.Integer('Color Index')

    source_comment_id = fields.Many2one(
        comodel_name="l10n_br_fiscal.comment",
        string="Comment Source",
        help='If this additional data segment was generated by a comment, the reference should be kept here.')

    is_computed_data = fields.Boolean(
        string='Computed Data',
        help='Signals if this fragment of additional data is calculated automatically.')

    additional_data = fields.Char(
        string='Additional Data',
        help='Data corresponding to this segment, which will be used to form the additional_data along with other segments.')

    @api.depends("additional_data")
    def _compute_name(self):
        for record in self:
            record.name = record.additional_data
